steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy:$BUILD_ID'
      - '--platform'
      - '${_PLATFORM}'
      - '--region'
      - '${_REGION}'
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy:$BUILD_ID'
logsBucket: '${_LOGS_BUCKET}'
substitutions:
  _SERVICE_NAME: 'ici'
  _PLATFORM: 'managed'
  _REGION: 'us-west1'
  _LOGS_BUCKET: 'gs://zip-myl-dev/logs'
