steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '-t',
        'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/test-hello:$BUILD_ID',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'run', 'deploy', 'test-hello',
        '--image', 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/test-hello:$BUILD_ID',
        '--region', 'us-west1',
        '--platform', 'managed',
        '--allow-unauthenticated',
      ]
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/test-hello:$BUILD_ID'
logsBucket: '${_LOGS_BUCKET}'
substitutions:
  _LOGS_BUCKET: 'gs://your-cloud-build-logs-bucket'