steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'CACHE_BUST=${_CACHE_BUST}', '-t', 'gcr.io/$PROJECT_ID/ici:$BUILD_ID', '.']
images:
  - 'gcr.io/$PROJECT_ID/ici:$BUILD_ID'
