steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'CACHE_BUST=$BUILD_ID', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'
      - '--platform'
      - '${_PLATFORM}'
      - '--region'
      - '${_REGION}'
options:
  logging: GCS_ONLY
substitutions:
    _IMAGE_NAME: "ici"
    _SERVICE_NAME: "ici"
    _PLATFORM: "managed"
    _REGION: "us-west1"
images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'
