steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'CACHE_BUST=$BUILD_ID', '-t', 'gcr.io/$PROJECT_ID/ici:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ici:$BUILD_ID'
      - '--platform'
      - '${_PLATFORM}'
      - '--region'
      - '${_REGION}'
options:
  logging: GCS_ONLY
images:
  - 'gcr.io/$PROJECT_ID/ici:$BUILD_ID'
