steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_IMAGE_NAME}:$BUILD_ID'
      - '--build-arg'
      - 'CACHE_BUST=$BUILD_ID'
      - '.'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_IMAGE_NAME}:$BUILD_ID'
      - '--platform'
      - '${_PLATFORM}'
      - '--region'
      - '${_REGION}'
      - '--quiet'
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_IMAGE_NAME}:$BUILD_ID'
logsBucket: '${_LOGS_BUCKET}'
options:
  logging: GCS_ONLY
substitutions:
  _SERVICE_NAME: 'zip-myl-dev'
  _PLATFORM: 'managed'
  _REGION: 'us-west1'
  _IMAGE_NAME: 'zip-myl-dev' # Default image name
  _LOGS_BUCKET: 'gs://zip-myl-dev/logs'
