# filepath: e:\zip-myl-dev\ici\cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ici:$BUILD_ID', '.']
images:
  - 'gcr.io/$PROJECT_ID/ici:$BUILD_ID'
logsBucket: 'gs://zip-myl-dev'
